# Generated by Django 6.0 on 2026-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateField()),
                ('meesho_amount', models.DecimalField(decimal_places=2, help_text='Price customer paid on Meesho', max_digits=8)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Your actual product cost', max_digits=8)),
                ('packing_cost', models.DecimalField(decimal_places=2, default=0, help_text='Packing/packaging cost', max_digits=8)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, help_text='Meesho commission/fees', max_digits=8)),
                ('bank_settlement', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually received in bank', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='product_price + packing_cost + platform_fees', max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='bank_settlement - total_cost', max_digits=8)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('awaiting', 'Awaiting'), ('transferred', 'Transferred to Bank')], default='awaiting', max_length=20)),
                ('product_condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('damaged', 'Damaged'), ('returned', 'Returned Damaged')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
